[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
hello_world_anchor = "6VA2S3f2DpcdbvwVBJ2cK8xJrJRfBASRkkKNj531kEB5"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/jereme/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
